name: medical-diagnosis-agent
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - pip:
      - langchain-core
      - langchain
      - langchain-community
      - langchain-experimental
      - langchain-groq
      - langchain_ollama
      - streamlit
      - python-dotenv
      - reportlab
